-- PostgreSQL schema: FINAL state equivalent to SQLite migrations 001-005.
-- Generated by scripts/gen-pg-schema.js, then reviewed. Money is BIGINT minor units (never floating point); timestamps are
-- ISO-8601 UTC TEXT exactly as in SQLite so both engines return identical values; booleans are 0/1 BIGINT with CHECKs.
CREATE OR REPLACE FUNCTION iso_now() RETURNS text LANGUAGE sql STABLE AS
$$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') $$;

CREATE TABLE restaurants (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                TEXT NOT NULL UNIQUE,
  name                TEXT NOT NULL,
  description         TEXT NOT NULL DEFAULT '',
  logo_url            TEXT,
  phone               TEXT,
  email               TEXT,
  address             TEXT,
  city                TEXT,
  currency            TEXT NOT NULL DEFAULT 'USD',
  tax_rate_bp         BIGINT NOT NULL DEFAULT 0 CHECK (tax_rate_bp BETWEEN 0 AND 10000), -- basis points
  delivery_fee_cents  BIGINT NOT NULL DEFAULT 0 CHECK (delivery_fee_cents >= 0),
  min_order_cents     BIGINT NOT NULL DEFAULT 0 CHECK (min_order_cents >= 0),
  accepting_orders    BIGINT NOT NULL DEFAULT 1 CHECK (accepting_orders IN (0,1)),
  is_active           BIGINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),  -- platform-level suspension
  is_demo             BIGINT NOT NULL DEFAULT 0 CHECK (is_demo IN (0,1)),
  created_at          TEXT NOT NULL DEFAULT (iso_now())
, owner_id BIGINT, whatsapp TEXT, cover_url TEXT, opening_hours TEXT, timezone TEXT NOT NULL DEFAULT 'Asia/Riyadh', latitude DOUBLE PRECISION, longitude DOUBLE PRECISION, approval_status TEXT NOT NULL DEFAULT 'pending'
  CHECK (approval_status IN ('pending','approved','rejected')), rejection_reason TEXT, commission_bp_override BIGINT CHECK (commission_bp_override IS NULL OR commission_bp_override BETWEEN 0 AND 10000), updated_at TEXT, custom_domain TEXT, commission_fixed_override BIGINT CHECK (commission_fixed_override IS NULL OR commission_fixed_override >= 0));

CREATE TABLE users (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  password_hash  TEXT NOT NULL,
  name           TEXT NOT NULL,
  phone          TEXT,
  role           TEXT NOT NULL CHECK (role IN ('super_admin','owner','staff','customer')),
  restaurant_id  BIGINT REFERENCES restaurants(id) ON DELETE CASCADE,
  is_active      BIGINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at     TEXT NOT NULL DEFAULT (iso_now()), token_version BIGINT NOT NULL DEFAULT 0, email_verified_at TEXT, updated_at TEXT, totp_secret_enc TEXT, totp_enabled BIGINT NOT NULL DEFAULT 0 CHECK (totp_enabled IN (0,1)), totp_last_step BIGINT,
  -- staff always belong to a restaurant; customers and super admins never do
  CHECK (
    (role IN ('owner','staff') AND (restaurant_id IS NOT NULL OR role = 'owner')) OR
    (role IN ('customer','super_admin') AND restaurant_id IS NULL)
  )
);

CREATE TABLE audit_logs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
  actor_role   TEXT,
  action       TEXT NOT NULL,
  target_type  TEXT,
  target_id    TEXT,
  details      TEXT,                                  -- JSON, never contains secrets
  ip           TEXT,
  created_at   TEXT NOT NULL DEFAULT (iso_now())
);

CREATE TABLE auth_tokens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type        TEXT NOT NULL CHECK (type IN ('password_reset','email_verify')),
  token_hash  TEXT NOT NULL UNIQUE,                   -- SHA-256 of the emailed token; the raw token is never stored
  expires_at  TEXT NOT NULL,
  used_at     TEXT,
  created_at  TEXT NOT NULL DEFAULT (iso_now())
);

CREATE TABLE backup_codes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash  TEXT NOT NULL,
  used_at    TEXT,
  created_at TEXT NOT NULL DEFAULT (iso_now()),
  UNIQUE (user_id, code_hash)
);

CREATE TABLE branches (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id  BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  name           TEXT NOT NULL,
  address        TEXT,
  phone          TEXT,
  created_at     TEXT NOT NULL DEFAULT (iso_now())
);

CREATE TABLE categories (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id  BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  name           TEXT NOT NULL,
  sort_order     BIGINT NOT NULL DEFAULT 0,
  UNIQUE (id, restaurant_id),
  UNIQUE (restaurant_id, name)
);

CREATE TABLE idempotency_keys (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  scope          TEXT NOT NULL,
  key            TEXT NOT NULL,
  request_hash   TEXT NOT NULL,
  response_status BIGINT,
  response_body  TEXT,
  created_at     TEXT NOT NULL DEFAULT (iso_now()),
  UNIQUE (user_id, scope, key)
);

CREATE TABLE orders (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id         BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  customer_id           BIGINT NOT NULL REFERENCES users(id),
  order_number          BIGINT NOT NULL,
  status                TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('awaiting_payment','pending','confirmed','preparing','ready',
                                          'out_for_delivery','delivered','cancelled','rejected')),
  order_type            TEXT NOT NULL CHECK (order_type IN ('delivery','pickup')),
  payment_method        TEXT NOT NULL DEFAULT 'cod' CHECK (payment_method IN ('card','cod')),
  payment_status        TEXT NOT NULL DEFAULT 'cod_pending'
                        CHECK (payment_status IN ('awaiting_payment','paid','failed','cancelled','cod_pending',
                                                  'cash_collected','refunded','partially_refunded')),
  customer_name         TEXT NOT NULL,
  customer_phone        TEXT NOT NULL,
  delivery_address      TEXT,
  delivery_latitude     DOUBLE PRECISION,
  delivery_longitude    DOUBLE PRECISION,
  notes                 TEXT,
  subtotal_cents        BIGINT NOT NULL CHECK (subtotal_cents >= 0),
  discount_cents        BIGINT NOT NULL DEFAULT 0 CHECK (discount_cents >= 0),
  tax_cents             BIGINT NOT NULL CHECK (tax_cents >= 0),
  delivery_fee_cents    BIGINT NOT NULL CHECK (delivery_fee_cents >= 0),
  platform_fee_cents    BIGINT NOT NULL DEFAULT 0 CHECK (platform_fee_cents >= 0),  -- customer-paid service fee, kept by the platform
  total_cents           BIGINT NOT NULL CHECK (total_cents >= 0),
  -- Snapshot of the marketplace split, fixed at order time so later setting changes never rewrite history
  commission_bp         BIGINT NOT NULL DEFAULT 0,
  commission_cents      BIGINT NOT NULL DEFAULT 0 CHECK (commission_cents >= 0),
  restaurant_amount_cents BIGINT NOT NULL DEFAULT 0 CHECK (restaurant_amount_cents >= 0),
  currency              TEXT NOT NULL,
  cancel_reason         TEXT,
  expires_at            TEXT,                         -- awaiting_payment orders are cancelled after this
  paid_at               TEXT,
  delivered_at          TEXT,
  created_at            TEXT NOT NULL DEFAULT (iso_now()),
  updated_at            TEXT NOT NULL DEFAULT (iso_now()), commission_fixed_cents BIGINT NOT NULL DEFAULT 0 CHECK (commission_fixed_cents >= 0),
  UNIQUE (id, restaurant_id),
  UNIQUE (restaurant_id, order_number),
  CHECK (total_cents = subtotal_cents - discount_cents + tax_cents + delivery_fee_cents + platform_fee_cents)
);

CREATE TABLE payments (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id                BIGINT NOT NULL,
  customer_id             BIGINT NOT NULL REFERENCES users(id),
  restaurant_id           BIGINT NOT NULL,
  provider                TEXT NOT NULL,                 -- 'tap' | 'cod'
  provider_transaction_id TEXT,
  amount_cents            BIGINT NOT NULL CHECK (amount_cents >= 0),
  currency                TEXT NOT NULL,                 -- order/payment currency
  settlement_currency     TEXT,                          -- filled from provider data when it differs
  payment_method          TEXT NOT NULL CHECK (payment_method IN ('card','cod')),
  payment_source          TEXT,                          -- e.g. VISA, MASTERCARD, MADA, APPLE_PAY as reported by provider
  status                  TEXT NOT NULL
                          CHECK (status IN ('initiated','pending','succeeded','failed','cancelled',
                                            'cod_pending','cash_collected','refunded','partially_refunded')),
  refunded_cents          BIGINT NOT NULL DEFAULT 0 CHECK (refunded_cents >= 0),
  estimated_fee_cents     BIGINT NOT NULL DEFAULT 0 CHECK (estimated_fee_cents >= 0),
  failure_reason          TEXT,
  created_at              TEXT NOT NULL DEFAULT (iso_now()),
  updated_at              TEXT NOT NULL DEFAULT (iso_now()),
  UNIQUE (order_id),
  UNIQUE (id, restaurant_id),
  CHECK (refunded_cents <= amount_cents),
  FOREIGN KEY (order_id, restaurant_id) REFERENCES orders(id, restaurant_id) ON DELETE CASCADE
);

CREATE TABLE refunds (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id          BIGINT NOT NULL,
  order_id            BIGINT NOT NULL,
  restaurant_id       BIGINT NOT NULL,
  amount_cents        BIGINT NOT NULL CHECK (amount_cents > 0),
  currency            TEXT NOT NULL,
  reason              TEXT NOT NULL,
  status              TEXT NOT NULL CHECK (status IN ('pending','succeeded','failed')),
  provider_refund_id  TEXT,
  idempotency_key     TEXT NOT NULL UNIQUE,
  requested_by        BIGINT REFERENCES users(id),
  failure_reason      TEXT,
  created_at          TEXT NOT NULL DEFAULT (iso_now()),
  updated_at          TEXT NOT NULL DEFAULT (iso_now()),
  FOREIGN KEY (payment_id, restaurant_id) REFERENCES payments(id, restaurant_id) ON DELETE CASCADE
);

CREATE TABLE payouts (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id       BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  amount_cents        BIGINT NOT NULL CHECK (amount_cents >= 0),
  currency            TEXT NOT NULL,
  settlement_currency TEXT,
  provider            TEXT NOT NULL,
  provider_payout_id  TEXT,
  period_start        TEXT NOT NULL,
  period_end          TEXT NOT NULL,
  status              TEXT NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','eligible','requested','processing','paid','failed','cancelled','reversed','manual_payout')),
  confirmation_source TEXT CHECK (confirmation_source IN ('provider','admin_manual')),
  failure_reason      TEXT,
  requested_at        TEXT,
  created_at          TEXT NOT NULL DEFAULT (iso_now()),
  updated_at          TEXT NOT NULL DEFAULT (iso_now()),
  paid_at             TEXT,
  UNIQUE (restaurant_id, period_start),
  CHECK (status != 'paid' OR (confirmation_source IS NOT NULL AND provider_payout_id IS NOT NULL))
);

CREATE TABLE ledger_entries (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id            BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  order_id                 BIGINT NOT NULL,
  payment_id               BIGINT,
  refund_id                BIGINT REFERENCES refunds(id),
  entry_type               TEXT NOT NULL CHECK (entry_type IN ('sale','refund','cod_commission')),
  gross_amount_cents       BIGINT NOT NULL,          -- signed: negative for refunds
  platform_commission_cents BIGINT NOT NULL,         -- signed
  platform_fee_cents       BIGINT NOT NULL DEFAULT 0, -- customer service fee retained by platform (signed)
  payment_fee_cents        BIGINT NOT NULL DEFAULT 0, -- provider fee charged to the restaurant (signed; 0 when platform bears it)
  restaurant_amount_cents  BIGINT NOT NULL,          -- signed net to restaurant (for cod_commission: the negative amount owed to platform)
  currency                 TEXT NOT NULL,
  eligible_at              TEXT,                      -- NULL until the order is delivered (refunds are eligible immediately)
  payout_id                BIGINT REFERENCES payouts(id),
  payout_status            TEXT NOT NULL DEFAULT 'unpaid' CHECK (payout_status IN ('unpaid','in_payout','paid')),
  payout_date              TEXT,
  settled_at               TEXT,                      -- cod_commission only: when the platform collected it
  created_at               TEXT NOT NULL DEFAULT (iso_now()),
  FOREIGN KEY (order_id, restaurant_id) REFERENCES orders(id, restaurant_id) ON DELETE CASCADE,
  CHECK (restaurant_amount_cents = gross_amount_cents - platform_commission_cents - platform_fee_cents - payment_fee_cents
         OR entry_type = 'cod_commission')
);

CREATE TABLE products (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id  BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  category_id    BIGINT,
  name           TEXT NOT NULL,
  description    TEXT NOT NULL DEFAULT '',
  price_cents    BIGINT NOT NULL CHECK (price_cents >= 0),
  image_url      TEXT,
  is_available   BIGINT NOT NULL DEFAULT 1 CHECK (is_available IN (0,1)),
  created_at     TEXT NOT NULL DEFAULT (iso_now()),
  UNIQUE (id, restaurant_id),
  FOREIGN KEY (category_id, restaurant_id) REFERENCES categories(id, restaurant_id)
);

CREATE TABLE option_groups (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id  BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  product_id     BIGINT NOT NULL,
  name           TEXT NOT NULL,
  min_select     BIGINT NOT NULL DEFAULT 0 CHECK (min_select >= 0),
  max_select     BIGINT NOT NULL DEFAULT 1 CHECK (max_select >= 1),
  sort_order     BIGINT NOT NULL DEFAULT 0,
  CHECK (min_select <= max_select),
  UNIQUE (id, restaurant_id),
  FOREIGN KEY (product_id, restaurant_id) REFERENCES products(id, restaurant_id) ON DELETE CASCADE
);

CREATE TABLE options (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id  BIGINT NOT NULL,
  group_id       BIGINT NOT NULL,
  name           TEXT NOT NULL,
  price_cents    BIGINT NOT NULL DEFAULT 0 CHECK (price_cents >= 0),
  is_available   BIGINT NOT NULL DEFAULT 1 CHECK (is_available IN (0,1)),
  sort_order     BIGINT NOT NULL DEFAULT 0,
  UNIQUE (id, restaurant_id),
  FOREIGN KEY (group_id, restaurant_id) REFERENCES option_groups(id, restaurant_id) ON DELETE CASCADE
);

CREATE TABLE order_items (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id          BIGINT NOT NULL,
  restaurant_id     BIGINT NOT NULL,
  product_id        BIGINT,
  product_name      TEXT NOT NULL,
  unit_price_cents  BIGINT NOT NULL CHECK (unit_price_cents >= 0),
  quantity          BIGINT NOT NULL CHECK (quantity BETWEEN 1 AND 100),
  line_total_cents  BIGINT NOT NULL CHECK (line_total_cents >= 0),
  FOREIGN KEY (order_id, restaurant_id) REFERENCES orders(id, restaurant_id) ON DELETE CASCADE,
  FOREIGN KEY (product_id, restaurant_id) REFERENCES products(id, restaurant_id) ON DELETE SET NULL
);

CREATE TABLE order_item_options (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_item_id    BIGINT NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,
  restaurant_id    BIGINT NOT NULL,
  option_id        BIGINT,
  group_name       TEXT NOT NULL,
  option_name      TEXT NOT NULL,
  price_cents      BIGINT NOT NULL CHECK (price_cents >= 0),
  FOREIGN KEY (option_id, restaurant_id) REFERENCES options(id, restaurant_id) ON DELETE SET NULL
);

CREATE TABLE order_status_history (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       BIGINT NOT NULL,
  restaurant_id  BIGINT NOT NULL,
  status         TEXT NOT NULL,
  changed_by     BIGINT REFERENCES users(id),
  created_at     TEXT NOT NULL DEFAULT (iso_now()),
  FOREIGN KEY (order_id, restaurant_id) REFERENCES orders(id, restaurant_id) ON DELETE CASCADE
);

CREATE TABLE payout_events (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payout_id         BIGINT NOT NULL REFERENCES payouts(id) ON DELETE CASCADE,
  from_status       TEXT,
  to_status         TEXT NOT NULL,
  source            TEXT NOT NULL CHECK (source IN ('provider','admin','system')),
  provider_event_id TEXT,
  actor_id          BIGINT REFERENCES users(id) ON DELETE SET NULL,
  details           TEXT,
  created_at        TEXT NOT NULL DEFAULT (iso_now())
);

CREATE TABLE plans (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              TEXT NOT NULL UNIQUE,
  name              TEXT NOT NULL,
  description       TEXT NOT NULL DEFAULT '',
  price_cents       BIGINT NOT NULL DEFAULT 0 CHECK (price_cents >= 0),
  currency          TEXT NOT NULL DEFAULT 'USD',
  max_menu_items    BIGINT,              -- NULL = unlimited
  max_branches      BIGINT,
  max_staff         BIGINT,
  analytics         BIGINT NOT NULL DEFAULT 0 CHECK (analytics IN (0,1)),
  advanced_reports  BIGINT NOT NULL DEFAULT 0 CHECK (advanced_reports IN (0,1)),
  is_active         BIGINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  sort_order        BIGINT NOT NULL DEFAULT 0
, billing_interval TEXT NOT NULL DEFAULT 'month' CHECK (billing_interval IN ('month','year')), trial_days BIGINT NOT NULL DEFAULT 0 CHECK (trial_days BETWEEN 0 AND 365), max_orders_per_month BIGINT, features TEXT NOT NULL DEFAULT '[]');

CREATE TABLE provider_settlements (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider             TEXT NOT NULL,
  provider_payout_id   TEXT NOT NULL,
  restaurant_id        BIGINT REFERENCES restaurants(id) ON DELETE SET NULL,   -- matched through the destination's wallet id; NULL = unmatched
  provider_wallet_id   TEXT,
  provider_merchant_id TEXT,
  amount_text          TEXT NOT NULL,   -- exactly as reported: the unit is not documented, so it is never used in arithmetic
  currency             TEXT,
  status_raw           TEXT NOT NULL,
  status               TEXT NOT NULL CHECK (status IN ('processing','paid','failed','unknown')),
  payout_date          TEXT,
  raw                  TEXT,            -- redacted provider JSON
  first_seen_at        TEXT NOT NULL DEFAULT (iso_now()),
  last_seen_at         TEXT NOT NULL DEFAULT (iso_now()),
  UNIQUE (provider, provider_payout_id)
);

CREATE TABLE reports (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id  BIGINT REFERENCES restaurants(id) ON DELETE SET NULL,
  order_id       BIGINT,
  category       TEXT NOT NULL CHECK (category IN ('restaurant','order','payment','food','account','other')),
  subject        TEXT NOT NULL,
  description    TEXT NOT NULL,
  status         TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','resolved','closed')),
  priority       TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')),
  admin_response TEXT,
  created_at     TEXT NOT NULL DEFAULT (iso_now()),
  updated_at     TEXT NOT NULL DEFAULT (iso_now()),
  resolved_at    TEXT
);

CREATE TABLE restaurant_customers (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id    BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  user_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  first_order_at   TEXT NOT NULL DEFAULT (iso_now()),
  UNIQUE (restaurant_id, user_id)
);

CREATE TABLE restaurant_payment_accounts (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id         BIGINT NOT NULL UNIQUE REFERENCES restaurants(id) ON DELETE CASCADE,
  payment_provider      TEXT NOT NULL,
  connected_account_id  TEXT,                       -- provider destination / sub-merchant id
  onboarding_status     TEXT NOT NULL DEFAULT 'not_started'
                        CHECK (onboarding_status IN ('not_started','in_progress','completed','rejected')),
  verification_status   TEXT NOT NULL DEFAULT 'unverified'
                        CHECK (verification_status IN ('unverified','pending','verified','rejected')),
  payout_account_status TEXT NOT NULL DEFAULT 'inactive'
                        CHECK (payout_account_status IN ('inactive','active','restricted')),
  payout_enabled        BIGINT NOT NULL DEFAULT 0 CHECK (payout_enabled IN (0,1)),
  created_at            TEXT NOT NULL DEFAULT (iso_now()),
  updated_at            TEXT NOT NULL DEFAULT (iso_now())
, application_submitted_at TEXT, legal_name TEXT, registration_number TEXT, contact_name TEXT, contact_phone TEXT, contact_email TEXT, country TEXT NOT NULL DEFAULT 'SA', settlement_currency TEXT, masked_bank TEXT, rejection_reason TEXT, last_verified_at TEXT, disabled_at TEXT, provider_wallet_id TEXT, provider_business_id TEXT, provider_live_mode BIGINT);

CREATE TABLE subscriptions (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id        BIGINT NOT NULL UNIQUE REFERENCES restaurants(id) ON DELETE CASCADE,
  plan_id              BIGINT NOT NULL REFERENCES plans(id),
  status               TEXT NOT NULL CHECK (status IN ('trialing','active','past_due','cancelled','expired','suspended')),
  price_cents          BIGINT NOT NULL DEFAULT 0 CHECK (price_cents >= 0),       -- price locked in when the plan was chosen
  currency             TEXT NOT NULL DEFAULT 'USD',
  billing_interval     TEXT NOT NULL DEFAULT 'month' CHECK (billing_interval IN ('month','year')),
  start_date           TEXT,
  end_date             TEXT,                                                      -- end of the current paid/free period
  trial_end            TEXT,
  cancelled_at         TEXT,
  provider             TEXT NOT NULL DEFAULT 'platform',
  provider_ref         TEXT,
  current_period_end   TEXT,
  created_at           TEXT NOT NULL DEFAULT (iso_now()),
  updated_at           TEXT NOT NULL DEFAULT (iso_now())
);

CREATE TABLE saas_invoices (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id    BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  subscription_id  BIGINT REFERENCES subscriptions(id) ON DELETE SET NULL,
  plan_id          BIGINT NOT NULL REFERENCES plans(id),
  amount_cents     BIGINT NOT NULL CHECK (amount_cents >= 0),
  currency         TEXT NOT NULL,
  billing_interval TEXT NOT NULL CHECK (billing_interval IN ('month','year')),
  period_start     TEXT NOT NULL,
  period_end       TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','paid','void','failed')),
  provider         TEXT,                 -- 'tap' | 'manual'
  provider_ref     TEXT,                 -- provider charge id, or the admin's reference for manual payments
  failure_reason   TEXT,
  created_at       TEXT NOT NULL DEFAULT (iso_now()),
  paid_at          TEXT,
  updated_at       TEXT NOT NULL DEFAULT (iso_now())
);

CREATE TABLE saas_invoice_refunds (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id         BIGINT NOT NULL REFERENCES saas_invoices(id) ON DELETE CASCADE,
  restaurant_id      BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  amount_cents       BIGINT NOT NULL CHECK (amount_cents > 0),
  currency           TEXT NOT NULL,
  status             TEXT NOT NULL CHECK (status IN ('pending','succeeded','failed')),
  provider           TEXT NOT NULL,
  provider_refund_id TEXT,
  idempotency_key    TEXT NOT NULL UNIQUE,
  reason             TEXT NOT NULL,
  failure_reason     TEXT,
  created_by         BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at         TEXT NOT NULL DEFAULT (iso_now())
);

CREATE TABLE settings (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL,
  updated_at  TEXT NOT NULL DEFAULT (iso_now()),
  updated_by  BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE subscription_charge_attempts (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id         BIGINT NOT NULL REFERENCES saas_invoices(id) ON DELETE CASCADE,
  restaurant_id      BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  attempt_no         BIGINT NOT NULL CHECK (attempt_no BETWEEN 1 AND 10),
  status             TEXT NOT NULL CHECK (status IN ('started','succeeded','failed')),
  provider_charge_id TEXT,
  failure_reason     TEXT,
  created_at         TEXT NOT NULL DEFAULT (iso_now()),
  UNIQUE (invoice_id, attempt_no)
);

CREATE TABLE subscription_payment_methods (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id         BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  provider              TEXT NOT NULL,
  provider_customer_id  TEXT NOT NULL,
  provider_card_id      TEXT NOT NULL,
  provider_agreement_id TEXT NOT NULL,
  brand                 TEXT,
  last4                 TEXT CHECK (last4 IS NULL OR last4 ~ '^[0-9]{4}$'),
  status                TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','removed')),
  created_at            TEXT NOT NULL DEFAULT (iso_now()),
  removed_at            TEXT,
  UNIQUE (provider, provider_card_id)
);

CREATE TABLE webhook_events (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider      TEXT NOT NULL,
  event_key     TEXT NOT NULL,                        -- provider event id, or object id + status when none is supplied
  event_type    TEXT,
  object_id     TEXT,
  payload       TEXT,
  status        TEXT NOT NULL DEFAULT 'received' CHECK (status IN ('received','processed','ignored','failed')),
  error         TEXT,
  received_at   TEXT NOT NULL DEFAULT (iso_now()),
  processed_at  TEXT,
  UNIQUE (provider, event_key)
);

ALTER TABLE restaurants ADD CONSTRAINT fk_restaurants_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL;

-- case-insensitive unique email (SQLite: COLLATE NOCASE). The application also lower-cases emails.
CREATE UNIQUE INDEX uq_users_email_ci ON users (lower(email));

CREATE INDEX idx_users_restaurant ON users(restaurant_id);
CREATE INDEX idx_branches_restaurant ON branches(restaurant_id);
CREATE INDEX idx_products_restaurant ON products(restaurant_id, category_id);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_restaurant ON order_items(restaurant_id, product_id);
CREATE INDEX idx_option_groups_product ON option_groups(product_id);
CREATE INDEX idx_options_group ON options(group_id);
CREATE INDEX idx_orders_restaurant ON orders(restaurant_id, status, created_at);
CREATE INDEX idx_orders_customer ON orders(customer_id, created_at);
CREATE INDEX idx_orders_awaiting ON orders(status, expires_at);
CREATE INDEX idx_oio_item ON order_item_options(order_item_id);
CREATE UNIQUE INDEX uq_payments_provider_txn ON payments(provider, provider_transaction_id) WHERE provider_transaction_id IS NOT NULL;
CREATE INDEX idx_payments_restaurant ON payments(restaurant_id, status, created_at);
CREATE INDEX idx_refunds_payment ON refunds(payment_id);
CREATE UNIQUE INDEX uq_ledger_sale ON ledger_entries(order_id, entry_type) WHERE entry_type IN ('sale','cod_commission');
CREATE UNIQUE INDEX uq_ledger_refund ON ledger_entries(refund_id) WHERE refund_id IS NOT NULL;
CREATE INDEX idx_ledger_restaurant ON ledger_entries(restaurant_id, payout_id, eligible_at);
CREATE INDEX idx_reports_status ON reports(status, created_at);
CREATE INDEX idx_audit_created ON audit_logs(created_at);
CREATE INDEX idx_subscriptions_status ON subscriptions(status, end_date);
CREATE INDEX idx_saas_invoices_restaurant ON saas_invoices(restaurant_id, status, created_at);
CREATE UNIQUE INDEX uq_saas_invoices_provider_ref ON saas_invoices(provider, provider_ref) WHERE provider = 'tap' AND provider_ref IS NOT NULL;
CREATE UNIQUE INDEX uq_saas_invoices_open ON saas_invoices(restaurant_id) WHERE status = 'open';
CREATE UNIQUE INDEX uq_restaurants_custom_domain ON restaurants(custom_domain) WHERE custom_domain IS NOT NULL;
CREATE UNIQUE INDEX uq_payment_accounts_connected ON restaurant_payment_accounts(payment_provider, connected_account_id) WHERE connected_account_id IS NOT NULL;
CREATE UNIQUE INDEX uq_payouts_provider_ref ON payouts(provider, provider_payout_id) WHERE provider_payout_id IS NOT NULL;
CREATE INDEX idx_payouts_status ON payouts(status, period_start);
CREATE UNIQUE INDEX uq_payout_events_provider ON payout_events(provider_event_id) WHERE provider_event_id IS NOT NULL;
CREATE INDEX idx_payout_events_payout ON payout_events(payout_id, id);
CREATE INDEX idx_saas_invoice_refunds_invoice ON saas_invoice_refunds(invoice_id, status);
CREATE INDEX idx_settlements_restaurant ON provider_settlements(restaurant_id, payout_date);
CREATE UNIQUE INDEX uq_sub_pm_active ON subscription_payment_methods(restaurant_id) WHERE status = 'active';

CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at THEN NEW.updated_at := iso_now(); END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_users_updated BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_restaurants_updated BEFORE UPDATE ON restaurants FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_orders_updated BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_payments_updated BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_refunds_updated BEFORE UPDATE ON refunds FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_reports_updated BEFORE UPDATE ON reports FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_saas_invoices_updated BEFORE UPDATE ON saas_invoices FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_subscriptions_updated BEFORE UPDATE ON subscriptions FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_payouts_updated BEFORE UPDATE ON payouts FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE OR REPLACE FUNCTION ledger_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'ledger entries are append-only' USING ERRCODE = '23514'; END $$;
CREATE TRIGGER trg_ledger_no_delete BEFORE DELETE ON ledger_entries FOR EACH ROW EXECUTE FUNCTION ledger_append_only();
